### PR TITLE
fix(form): add correct render props ref type

### PR DESCRIPTION
**Pull request by BleedingDev**
This fixes the problem we talked about at Lisci.

### CODE REVIEW

**Comment by pegak** [comment]
It infers automatically based on the type. I don't know if you have access to Lisci anymore, but when I fixed locally my node_modules, it inferred correctly. You do not need to pass generic, it can infer based on the passed value. Also if you do not pass it, you have default value as well. :)

**Review by nx-jan-fischer — APPROVED** [review]

**Comment by nx-jan-fischer** [comment]
I merged it and try it currently locally. For me it does not work in this way. Are you sure, that you tried it with an non HTMLElement field?

**Comment by pegak** [comment]
Was the new version released? I updated to the latest @nx-kit/form, which is 0.1.23. I still see this in `ControlledInput.types.ts` in our `node_modules`:
```typescript
import React from 'react';
export declare type RenderProps = {
    onBlur: () => void;
    onChange: (value: any) => void;
    value: React.Key;
    hasError: boolean;
    ref: React.Ref<HTMLElement>;
};
export declare type ControlledInputProps = {
    name: string;
    render: (props: RenderProps) => React.ReactElement;
    validation?: any;
};
```

I found out that I forgot one more thing in this PR. Update other stuff to pass the `<T>`.
```typescript
import React from 'react';
export declare type RenderProps<T extends HTMLElement = HTMLElement> = {
    onBlur: () => void;
    onChange: (value: any) => void;
    value: React.Key;
    hasError: boolean;
    ref: React.Ref<T>;
};
export declare type ControlledInputProps<T> = {
    name: string;
    render: (props: RenderProps<T>) => React.ReactElement;
    validation?: any;
};
```
and
```typescript
export declare const ControlledInput: ({ name, render, validation }: ControlledInputProps<T>) => JSX.Element;
```

I can use our MultiSelect with this:
`export const MultiSelectField = forwardRef<HTMLSelectElement | null, MultiSelectFieldProps>(`, which in your branch was previously `export const MultiSelectField = forwardRef<HTMLElement | null, MultiSelectFieldProps>(`. I removed the `@ts-ignore` and it works correctly. If I change the type back, it yells.

image
image

**Comment by nx-jan-fischer** [comment]
No, I had a little trouble with updating all react-aria packages. I will let you know here, if it's released.

But this looks wrong: `export declare const ControlledInput: ({ name, render, validation }: ControlledInputProps<T>) => JSX.Element;`

I have it now like this: `export declare const ControlledInput: <T extends HTMLElement = HTMLElement>({ name, render, validation }: ControlledInputProps<T>) => JSX.Element;`

**Comment by nx-jan-fischer** [comment]
@pegak It's now published on npm. Please update all @nx-kit libs. It should work like this now:

`<Form.ControlledInput<HTMLSelectElement> />`

**Pull request merged**
